title: Kirill Sukhorukov
logo: /assets/img/my_photo.png
description: Beginning Data Scientist. I have been actively studying Data Science for 1-2 years. Recently I have started to delve more into Deep Learning and neural networks. I am TeamLead and the main Data Scientist of the team, with which I actively participate in various hackathons. I lead a healthy lifestyle, I am single. I am always open to gaining new knowledge and experience.
# show_downloads: true
theme: jekyll-theme-minimal